Repository hashicorp/terraform-provider-awscc, pull requests merged in 2022-05, with the labels that each got.

#496 .github/workflows/release: restore workflow trigger to tag push
  .github/workflows/release.yml
Labels: github_actions

#510 Prevent infinite loop if an API error is returned when waiting for an async operation to complete
  CHANGELOG.md
  internal/aws/ec2/vpc_resource_test.go
  internal/service/cloudcontrol/waiter.go
Labels: bug, runtime-handling

#512 Add `AttributePlanModifier` that suppresses semantically insignificant differences between JSON strings
  internal/generic/jsonstring.go
  internal/generic/jsonstring_test.go
Labels: enhancement, runtime-handling
