Repository hashicorp/terraform-provider-awscc, pull requests merged in 2023-07, with the labels that each got.

#1035 docs: add example for awscc_ecs_capacity_provider
  docs/resources/ecs_capacity_provider.md
  examples/resources/awscc_ecs_capacity_provider/ecs_capacity_provider.tf
  templates/resources/ecs_capacity_provider.md.tmpl
Labels: needs-triage

#1032 docs - awscc_rds_db_cluster
  docs/resources/rds_db_cluster.md
  examples/resources/awscc_rds_db_cluster/rds_db_cluster.tf
  templates/resources/rds_db_cluster.md.tmpl
Labels: needs-triage

#1052 docs - location_map
  docs/resources/location_map.md
  examples/resources/awscc_location_map/basic.tf
  templates/resources/location_map.md.tmpl
Labels: needs-triage

#1027 docs: add example for wafv2_logging_configuration
  docs/resources/wafv2_logging_configuration.md
  examples/resources/awscc_wafv2_logging_configuration/wafv2_logging_configuration.tf
  examples/resources/awscc_wafv2_logging_configuration/wafv2_logging_configuration_logging_filter.tf
  examples/resources/awscc_wafv2_logging_configuration/wafv2_logging_configuration_redacted_fields.tf
  templates/resources/wafv2_logging_configuration.md.tmpl
Labels: documentation, waiting-response, service/wafv2

#1038 docs: add example for: awscc_ec2_host
  docs/resources/ec2_host.md
  examples/resources/awscc_ec2_host/ec2_host_family.tf
  examples/resources/awscc_ec2_host/ec2_host_type.tf
  templates/resources/ec2_host.md.tmpl
Labels: needs-triage

#1047 docs - awscc_amplify_branch
  docs/resources/amplify_branch.md
  examples/resources/awscc_amplify_branch/amplify_branch.tf
  examples/resources/awscc_amplify_branch/multi_branch.tf
  examples/resources/awscc_amplify_branch/single_branch.tf
  templates/resources/amplify_branch.md.tmpl
Labels: needs-triage

#1042 docs: elasticloadbalancingv2_target_group
  docs/resources/elasticloadbalancingv2_target_group.md
  examples/resources/awscc_elasticloadbalancingv2_target_group/elasticloadbalancingv2_target_group_alb.tf
  examples/resources/awscc_elasticloadbalancingv2_target_group/elasticloadbalancingv2_target_group_instance.tf
  examples/resources/awscc_elasticloadbalancingv2_target_group/elasticloadbalancingv2_target_group_ip.tf
  examples/resources/awscc_elasticloadbalancingv2_target_group/elasticloadbalancingv2_target_group_lambda.tf
  templates/resources/elasticloadbalancingv2_target_group.md.tmpl
Labels: needs-triage

#1050 docs: add example for :awscc_amplify_domain
  docs/resources/amplify_domain.md
  examples/resources/awscc_amplify_domain/amplify_domain.tf
  templates/resources/amplify_domain.md.tmpl
Labels: needs-triage

#1060 doc: oam-link
  docs/resources/oam_link.md
  examples/resources/awscc_oam_link/oam_link_example.tf
  templates/resources/oam_link.md.tmpl
Labels: needs-triage

#1040 docs - ec2_vpn_gateway
  docs/resources/ec2_vpn_gateway.md
  examples/resources/awscc_ec2_vpn_gateway/ec2_vpn_gateway.tf
  examples/resources/awscc_ec2_vpn_gateway/ec2_vpn_gateway_asn.tf
  templates/resources/ec2_vpn_gateway.md.tmpl
Labels: needs-triage

#1048 docs: add example for awscc_amplify_app
  docs/resources/amplify_app.md
  examples/resources/awscc_amplify_app/amplify_app.tf
  examples/resources/awscc_amplify_app/auto_branch_creation.tf
  examples/resources/awscc_amplify_app/basic_authorization.tf
  examples/resources/awscc_amplify_app/repository_with_tokens.tf
  examples/resources/awscc_amplify_app/rewrites_and_redirects.tf
  templates/resources/amplify_app.md.tmpl
Labels: documentation, service/amplify

#1068 docs: add example for:awscc_ec2_placement_group
  docs/resources/ec2_placement_group.md
  examples/resources/awscc_ec2_placement_group/placement_group_cluster.tf
  examples/resources/awscc_ec2_placement_group/placement_group_partition.tf
  examples/resources/awscc_ec2_placement_group/placement_group_spread.tf
  templates/resources/ec2_placement_group.md.tmpl
Labels: documentation, examples, service/ec2

#1095 docs: connect_integration_association
  docs/resources/connect_integration_association.md
  examples/resources/awscc_connect_integration_association/connect_integration_association_lambda.tf
  examples/resources/awscc_connect_integration_association/connect_integration_association_lex.tf
  templates/resources/connect_integration_association.md.tmpl
Labels: documentation, examples, service/connect

#1082 docs - networkmanager_global_network
  docs/resources/networkmanager_global_network.md
  examples/resources/awscc_networkmanager_global_network/basic.tf
  templates/resources/networkmanager_global_network.md.tmpl
Labels: needs-triage

#1085 docs - networkmanager_transit_gateway_registration
  docs/resources/networkmanager_transit_gateway_registration.md
  examples/resources/awscc_networkmanager_transit_gateway_registration/basic.tf
  templates/resources/networkmanager_transit_gateway_registration.md.tmpl
Labels: needs-triage

#1087 docs - networkmanager_transit_gateway_peering
  docs/resources/networkmanager_transit_gateway_peering.md
  examples/resources/awscc_networkmanager_transit_gateway_peering/basic.tf
  templates/resources/networkmanager_transit_gateway_peering.md.tmpl
Labels: needs-triage

#1075 docs - connect_phone_number
  docs/resources/connect_phone_number.md
  examples/resources/awscc_connect_phone_number/basic.tf
  examples/resources/awscc_connect_phone_number/with_prefix.tf
  templates/resources/connect_phone_number.md.tmpl
Labels: needs-triage

#1078 docs - connect_hours_of_operation
  docs/resources/connect_hours_of_operation.md
  examples/resources/awscc_connect_hours_of_operation/basic.tf
  templates/resources/connect_hours_of_operation.md.tmpl
Labels: needs-triage

#1080 docs - iam_service_linked_role
  docs/resources/iam_service_linked_role.md
  examples/resources/awscc_iam_service_linked_role/basic.tf
  examples/resources/awscc_iam_service_linked_role/custom_suffix.tf
  templates/resources/iam_service_linked_role.md.tmpl
Labels: needs-triage

#1088 docs - omics_sequence_store
  docs/resources/omics_sequence_store.md
  examples/resources/awscc_omics_sequence_store/basic.tf
  examples/resources/awscc_omics_sequence_store/fallback_location.tf
  examples/resources/awscc_omics_sequence_store/sse_config.tf
  templates/resources/omics_sequence_store.md.tmpl
Labels: needs-triage

#1081 docs - ec2_customer_gateway
  docs/resources/ec2_customer_gateway.md
  examples/resources/awscc_ec2_customer_gateway/basic.tf
  examples/resources/awscc_ec2_customer_gateway/device_name.tf
  templates/resources/ec2_customer_gateway.md.tmpl
Labels: needs-triage

#1079 docs - connect_prompt
  docs/resources/connect_prompt.md
  examples/resources/awscc_connect_prompt/basic.tf
  templates/resources/connect_prompt.md.tmpl
Labels: needs-triage
