Repository hashicorp/terraform-provider-awscc, pull requests merged in 2024-09, with the labels that each got.

#1982 docs: added example for awscc_rekognition_project
  docs/resources/rekognition_project.md
  examples/resources/awscc_rekognition_project/rekognition_project.tf
  templates/resources/rekognition_project.md.tmpl
Labels: documentation, examples, partner, service/rekognition

#1981 docs: added example for awscc_rekognition_collection
  docs/resources/rekognition_collection.md
  examples/resources/awscc_rekognition_collection/rekognition_collection.tf
  templates/resources/rekognition_collection.md.tmpl
Labels: documentation, examples, partner, service/rekognition

#1988 Add working board composite action
  .github/actions/community_check/README.md
  .github/actions/team_working_board/README.md
  .github/actions/team_working_board/action.yml
Labels: prioritized

#1777 Introduce workflow to automate GitHub Projects
  .github/workflows/projects.yml
Labels: github_actions

#1773 Add workflow to handle regressions
  .github/workflows/regressions.yml
Labels: github_actions

#1999 Update CHANGELOG.md after v1.13.0
  CHANGELOG.md
Labels: prioritized

#2000 [GHA] Use app token for new changelog version step
  .github/workflows/release.yml
Labels: prioritized

#2009 Add team as GitHub workflow owners
  CODEOWNERS
Labels: prioritized

#1993 docs: added example for awscc_route53profiles_profile
  docs/resources/route53profiles_profile.md
  examples/resources/awscc_route53profiles_profile/route53profiles_profile.tf
  templates/resources/route53profiles_profile.md.tmpl
Labels: documentation, examples, partner, service/route53profiles

#1994 docs: added example for awscc_iotevents_input
  docs/resources/iotevents_input.md
  examples/resources/awscc_iotevents_input/iotevents_input.tf
  templates/resources/iotevents_input.md.tmpl
Labels: documentation, examples, service/iotevents, partner

#2008 Add team feed integration for AWSCC
  .github/workflows/label-notifications.yml
  .github/workflows/pull_request_feed.yml
  .github/workflows/release-tag.yml
Labels: prioritized

#2007 docs: added examples for awscc_sagemaker_cluster
  CHANGELOG.md
  docs/resources/sagemaker_cluster.md
  examples/resources/awscc_sagemaker_cluster/import.sh
  examples/resources/awscc_sagemaker_cluster/sagemaker_cluster_eks.tf
  examples/resources/awscc_sagemaker_cluster/sagemaker_cluster_slurm.tf
  internal/aws/sagemaker/cluster_resource_gen.go
  internal/aws/sagemaker/cluster_resource_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/import_examples_gen.json
  internal/provider/plural_data_sources.go
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
  internal/service/cloudformation/schemas/AWS_SageMaker_Cluster.json
  templates/resources/sagemaker_cluster.md.tmpl
Labels: new-resource, service/sagemaker, partner

#2013 [Internal] Adds maintainer approval to feed
  .github/workflows/feed-approval.yml
Labels: prioritized

#2017 docs: ec2_network_insights_access_scope_analysis
  docs/resources/ec2_network_insights_access_scope_analysis.md
  examples/resources/awscc_ec2_network_insights_access_scope_analysis/basic.tf
  templates/resources/ec2_network_insights_access_scope_analysis.md.tmpl
Labels: documentation, examples, service/ec2, partner

#2015 fix: reference path in example awscc_sagemaker_cluster
  docs/resources/sagemaker_cluster.md
  examples/resources/awscc_sagemaker_cluster/sagemaker_cluster_eks.tf
Labels: needs-triage, partner

#2019 [Internal] Feed - Notify on maintainer comment
  .github/workflows/feed-comments.yml
Labels: prioritized

#2018 [Internal] Fixes for approval feed integration
  .github/workflows/feed-approval.yml
Labels: prioritized

#2028 add CHANGELOG entry for #2022
  CHANGELOG.md
Labels: prioritized

#2001 Unsuppress: awscc_events_connection
  CHANGELOG.md
  docs/data-sources/events_connection.md
  docs/resources/events_connection.md
  examples/resources/awscc_events_connection/connection_with_api_key_authorizer.tf
  examples/resources/awscc_events_connection/connection_with_oauth_authorizer.tf
  examples/resources/awscc_events_connection/import.sh
  internal/aws/events/connection_resource_gen.go
  internal/aws/events/connection_resource_gen_test.go
  internal/aws/events/connection_singular_data_source_gen.go
  internal/aws/events/connection_singular_data_source_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/import_examples_gen.json
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
  templates/resources/events_connection.md.tmpl
Labels: bug, documentation, examples, partner

#2037 [chore] Update for goreleaser deprecations
  .github/goreleaser-cross-compiler-test.yml
  .goreleaser.yml
Labels: prioritized

#2029 provider: Enable IAM role chaining
  CHANGELOG.md
  docs/index.md
  go.mod
  go.sum
  internal/provider/provider.go
Labels: prioritized

#2043 provider: Revert breaking change from IAM role chaining
  CHANGELOG.md
  docs/index.md
  internal/provider/provider.go
Labels: prioritized

#2042 [chore] Add META.d folder to repository
  META.d/_summary.yaml
Labels: prioritized
