Repository hashicorp/terraform-provider-awscc, pull requests merged in 2024-10, with the labels that each got.

#2027 Fix for unchecked pointer read of resource Identifier
  CHANGELOG.md
  internal/generic/resource.go
Labels: bug, crash, prioritized

#2061 chore: add help make target
  GNUmakefile
Labels: prioritized

#2072 Add new resources & data sources to correct CHANGELOG section
  CHANGELOG.md
Labels: prioritized

#2049 Feat: Unsuppress controltower landing zone
  CHANGELOG.md
  docs/data-sources/controltower_landing_zone.md
  docs/data-sources/controltower_landing_zones.md
  docs/resources/controltower_landing_zone.md
  examples/resources/awscc_controltower_landing_zone/controltower_landing_zone.tf
  examples/resources/awscc_controltower_landing_zone/import.sh
  internal/aws/controltower/landing_zone_plural_data_source_gen.go
  internal/aws/controltower/landing_zone_plural_data_source_gen_test.go
  internal/aws/controltower/landing_zone_resource_gen.go
  internal/aws/controltower/landing_zone_resource_gen_test.go
  internal/aws/controltower/landing_zone_singular_data_source_gen.go
  internal/aws/controltower/landing_zone_singular_data_source_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/import_examples_gen.json
  internal/provider/plural_data_sources.go
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
  templates/resources/controltower_landing_zone.md.tmpl
Labels: enhancement, new-data-source, new-resource, partner, service/controltower, prioritized
