Repository hashicorp/terraform-provider-awscc, pull requests merged in 2025-02, with the labels that each got.

#2106 docs: added example for resilience hub resiliency policy
  docs/resources/resiliencehub_resiliency_policy.md
  examples/resources/awscc_resiliencehub_resiliency_policy/main.tf
Labels: documentation, examples, service/resiliencehub

#2202 provider: build with Go 1.23.5
  .go-version
  go.mod
  tools/go.mod
  tools/go.sum
Labels: prioritized

#2208 fix: pagination on plural datasources
  internal/service/cloudcontrol/list.go
Labels: partner

#2219 fix: pcs cluster template info
  docs/resources/pcs_cluster.md
  examples/resources/awscc_pcs_cluster/main.tf
  templates/resources/pcs_cluster.md.tmpl
Labels: needs-triage, partner

#2221 format CHANGELOG
  CHANGELOG.md
Labels: prioritized
