Repository hashicorp/terraform-provider-awscc, pull requests merged in 2025-01, with the labels that each got.

#2161 docs: updated service labels
  infrastructure/repository/labels-service.tf
Labels: documentation, examples, partner

#2088 Added a few examples for awscc_eks
  docs/resources/eks_addon.md
  docs/resources/eks_pod_identity_association.md
  examples/resources/awscc_eks_addon/eks_addon.tf
  examples/resources/awscc_eks_addon/eks_addon_ebs_csi_driver.tf
  examples/resources/awscc_eks_addon/eks_addon_vpc_cni.tf
  examples/resources/awscc_eks_pod_identity_association/eks_pod_identity_association.tf
  templates/resources/eks_addon.md.tmpl
  templates/resources/eks_pod_identity_association.md.tmpl
Labels: documentation, examples, service/eks

#2172 ci: fix goreleaser deprecation warning
  .goreleaser.yml
Labels: prioritized
