Repository hashicorp/terraform-provider-awscc, pull requests merged in 2025-07, with the labels that each got.

#2359 refactor import example cli
  go.mod
  go.sum
  internal/provider/generators/import-examples/main.go
  internal/provider/generators/schema/imports.tmpl
  internal/provider/import_examples_gen.json
Labels: prioritized

#2369 Suppression Resolution: Write Only Attributes
  docs/data-sources/elasticloadbalancingv2_listener.md
  docs/data-sources/elasticloadbalancingv2_listener_rule.md
  docs/data-sources/elasticloadbalancingv2_listener_rules.md
  docs/data-sources/elasticloadbalancingv2_listeners.md
  docs/resources/elasticloadbalancingv2_listener.md
  docs/resources/elasticloadbalancingv2_listener_rule.md
  examples/resources/awscc_elasticloadbalancingv2_listener/import-by-string-id.tf
  examples/resources/awscc_elasticloadbalancingv2_listener/import.sh
  examples/resources/awscc_elasticloadbalancingv2_listener_rule/import-by-string-id.tf
  examples/resources/awscc_elasticloadbalancingv2_listener_rule/import.sh
  internal/aws/elasticloadbalancingv2/listener_plural_data_source_gen.go
  internal/aws/elasticloadbalancingv2/listener_plural_data_source_gen_test.go
  internal/aws/elasticloadbalancingv2/listener_resource_gen.go
  internal/aws/elasticloadbalancingv2/listener_resource_gen_test.go
  internal/aws/elasticloadbalancingv2/listener_rule_plural_data_source_gen.go
  internal/aws/elasticloadbalancingv2/listener_rule_plural_data_source_gen_test.go
  internal/aws/elasticloadbalancingv2/listener_rule_resource_gen.go
  internal/aws/elasticloadbalancingv2/listener_rule_resource_gen_test.go
  internal/aws/elasticloadbalancingv2/listener_rule_singular_data_source_gen.go
  internal/aws/elasticloadbalancingv2/listener_rule_singular_data_source_gen_test.go
  internal/aws/elasticloadbalancingv2/listener_singular_data_source_gen.go
  internal/aws/elasticloadbalancingv2/listener_singular_data_source_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/import_examples_gen.json
  internal/provider/plural_data_sources.go
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
Labels: code-generation

#2378 Update `version/VERSION` for `v1.49.0`
  version/VERSION
Labels: prioritized

#2366 Suppression resolution: map of sets of objects data type
  docs/data-sources/apigatewayv2_integration.md
  docs/data-sources/apigatewayv2_integrations.md
  docs/data-sources/appconfig_extension.md
  docs/data-sources/appconfig_extensions.md
  docs/resources/apigatewayv2_integration.md
  docs/resources/appconfig_extension.md
  examples/resources/awscc_apigatewayv2_integration/import-by-string-id.tf
  examples/resources/awscc_apigatewayv2_integration/import.sh
  examples/resources/awscc_appconfig_extension/import-by-string-id.tf
  examples/resources/awscc_appconfig_extension/import.sh
  internal/aws/apigatewayv2/integration_plural_data_source_gen.go
  internal/aws/apigatewayv2/integration_plural_data_source_gen_test.go
  internal/aws/apigatewayv2/integration_resource_gen.go
  internal/aws/apigatewayv2/integration_resource_gen_test.go
  internal/aws/apigatewayv2/integration_singular_data_source_gen.go
  internal/aws/apigatewayv2/integration_singular_data_source_gen_test.go
  internal/aws/appconfig/extension_plural_data_source_gen.go
  internal/aws/appconfig/extension_plural_data_source_gen_test.go
  internal/aws/appconfig/extension_resource_gen.go
  internal/aws/appconfig/extension_resource_gen_test.go
  internal/aws/appconfig/extension_singular_data_source_gen.go
  internal/aws/appconfig/extension_singular_data_source_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/generators/shared/codegen/emitter.go
  internal/provider/import_examples_gen.json
  internal/provider/plural_data_sources.go
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
Labels: code-generation, resource-suppression

#2371 Suppression Resolution: Array of Set of Object
  CHANGELOG.md
  docs/data-sources/accessanalyzer_analyzer.md
  docs/resources/accessanalyzer_analyzer.md
  internal/aws/accessanalyzer/analyzer_resource_gen.go
  internal/aws/accessanalyzer/analyzer_singular_data_source_gen.go
  internal/provider/all_schemas.hcl
  internal/provider/generators/shared/codegen/emitter.go
  internal/service/cloudformation/schemas/AWS_AccessAnalyzer_Analyzer.json
  internal/update/suppressions_checkout.txt
Labels: prioritized

#2368 Suppression Resolution: List of Key-Value Maps
  CHANGELOG.md
  docs/data-sources/omics_annotation_store.md
  docs/data-sources/omics_annotation_stores.md
  docs/data-sources/scheduler_schedule.md
  docs/data-sources/scheduler_schedules.md
  docs/resources/omics_annotation_store.md
  docs/resources/scheduler_schedule.md
  examples/resources/awscc_omics_annotation_store/import-by-string-id.tf
  examples/resources/awscc_omics_annotation_store/import.sh
  examples/resources/awscc_scheduler_schedule/import-by-string-id.tf
  examples/resources/awscc_scheduler_schedule/import.sh
  internal/aws/omics/annotation_store_plural_data_source_gen.go
  internal/aws/omics/annotation_store_plural_data_source_gen_test.go
  internal/aws/omics/annotation_store_resource_gen.go
  internal/aws/omics/annotation_store_resource_gen_test.go
  internal/aws/omics/annotation_store_singular_data_source_gen.go
  internal/aws/omics/annotation_store_singular_data_source_gen_test.go
  internal/aws/scheduler/schedule_plural_data_source_gen.go
  internal/aws/scheduler/schedule_plural_data_source_gen_test.go
  internal/aws/scheduler/schedule_resource_gen.go
  internal/aws/scheduler/schedule_resource_gen_test.go
  internal/aws/scheduler/schedule_singular_data_source_gen.go
  internal/aws/scheduler/schedule_singular_data_source_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/generators/shared/codegen/emitter.go
  internal/provider/import_examples_gen.json
  internal/provider/plural_data_sources.go
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
Labels: code-generation

#2723 Revert "Suppression Resolution: List of Key-Value Maps"
  CHANGELOG.md
  docs/data-sources/omics_annotation_store.md
  docs/data-sources/omics_annotation_stores.md
  docs/data-sources/scheduler_schedule.md
  docs/data-sources/scheduler_schedules.md
  docs/resources/omics_annotation_store.md
  docs/resources/scheduler_schedule.md
  examples/resources/awscc_omics_annotation_store/import-by-string-id.tf
  examples/resources/awscc_omics_annotation_store/import.sh
  examples/resources/awscc_scheduler_schedule/import-by-string-id.tf
  examples/resources/awscc_scheduler_schedule/import.sh
  internal/aws/omics/annotation_store_plural_data_source_gen.go
  internal/aws/omics/annotation_store_plural_data_source_gen_test.go
  internal/aws/omics/annotation_store_resource_gen.go
  internal/aws/omics/annotation_store_resource_gen_test.go
  internal/aws/omics/annotation_store_singular_data_source_gen.go
  internal/aws/omics/annotation_store_singular_data_source_gen_test.go
  internal/aws/scheduler/schedule_plural_data_source_gen.go
  internal/aws/scheduler/schedule_plural_data_source_gen_test.go
  internal/aws/scheduler/schedule_resource_gen.go
  internal/aws/scheduler/schedule_resource_gen_test.go
  internal/aws/scheduler/schedule_singular_data_source_gen.go
  internal/aws/scheduler/schedule_singular_data_source_gen_test.go
  internal/provider/all_schemas.hcl
  internal/provider/generators/shared/codegen/emitter.go
  internal/provider/import_examples_gen.json
  internal/provider/plural_data_sources.go
  internal/provider/resources.go
  internal/provider/singular_data_sources.go
Labels: resource-suppression, prioritized
